services:
  - type: web
    name: sentiment-analysis-backend
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r backend/requirements-minimal.txt --no-cache-dir"
    startCommand: "python backend/main_mvc.py"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
